import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { Charmonman } from "@next/font/google";
import { Fragment } from "react";

const charmonman = Charmonman({
  weight: "400",
  variable: "--charmonman-font",
});

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <Fragment>
      <Head>
        <title>To The Moon 🌕App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌕</text></svg>"
        />
      </Head>
      <main className={`container mx-auto flex min-h-screen flex-col items-center justify-center p-4 ${charmonman.className}`}>
        <h1
          className={`text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem] ${charmonman.className}`}
        >
          To The <span className="text-yellow-400">Moon 🌕</span> App
        </h1>
        <AuthShowcase />
      </main>
    </Fragment>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();
  const { data: sessionData } = useSession();
  return (
    <div
      className={`flex flex-col items-center justify-center gap-2 ${charmonman.className}`}
    >
      {sessionData && (
        <>
          <img
            src={sessionData?.user?.image as string}
            alt={sessionData?.user?.name as string}
            style={{
              borderRadius: "50%",
              width: "100px",
              height: "100px",
              margin: "0 auto",
              display: "block",
            }}
          />
          <p className={`text-2xl text-blue-500 ${charmonman.className}`}>
            เข้าสู่ระบบด้วย {sessionData?.user?.name}
          </p>
        </>
      )}
      {secretMessage && (
        <p className={`text-2xl text-blue-500 ${charmonman.className}`}>
          {secretMessage}
        </p>
      )}
      <button
        className={`rounded-md border border-brow bg-yellow-50 px-4 py-2 text-xl shadow-lg hover:bg-yellow-100 ${charmonman.className}`}
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "ออกจากระบบ" : "เข้าสู่ระบบ"}
      </button>
    </div>
  );
};
